name: linksco_example
description: linkable example

publish_to: none

version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.0.9
  linksco:
    path: ../

flutter:
  uses-material-design: true
